name: Automatic Release

on:
  push:
    branches: [ dev ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: make
      run: |
        make clean -i
        make USER_CFLAGS=-DDEBUG
    - uses: actions/upload-artifact@v2
      with:
        name: "kernel"
        path: | 
            bin/*
